name: universities
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.5
  sqflite: ^2.0.3+1
  path_provider: ^2.0.11
  salomon_bottom_bar: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/Montserrat-Medium.ttf
        - asset: assets/Montserrat-Bold.ttf
        - asset: assets/Montserrat-MediumItalic.ttf
        - asset: assets/Montserrat-BoldItalic.ttf
        - asset: assets/Montserrat-Regular.ttf
        - asset: assets/Montserrat-Italic.ttf
        - asset: assets/Montserrat-Thin.ttf
        - asset: assets/Montserrat-ThinItalic.ttf
